version: "3.8"

name: simple_ia_chat

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - ollama_net

  streamlit:
    build: ./streamlit_webapp/
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    networks:
      - ollama_net

volumes:
  ollama_data:

networks:
  ollama_net:
    driver: bridge